### ISSUE TITLE
Unknown column 's1hago'

### ISSUE THREAD

**Issue by fvictorio** [ethgasstation/ethgasstation-backend#11]
Hello, I'm getting the following error:

<pre>
[Errno 2] No such file or directory: '/home/fvictorio/repos/json/ethgasAPI.json'
Traceback (most recent call last):
  File "/home/fvictorio/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/home/fvictorio/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
  File "/home/fvictorio/.local/lib/python3.5/site-packages/mysql/connector/cursor.py", line 664, in executemany
    return self.execute(stmt)
  File "/home/fvictorio/.local/lib/python3.5/site-packages/mysql/connector/cursor.py", line 561, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/fvictorio/.local/lib/python3.5/site-packages/mysql/connector/connection.py", line 525, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/fvictorio/.local/lib/python3.5/site-packages/mysql/connector/connection.py", line 427, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): <b>Unknown column 's1hago' in 'field list'</b>
</pre>

I'm running this against a Rinkeby node, started with the following command:

```
geth --rinkeby --rpc --rpcapi="db,eth,net,web3,personal,txpool" console 2>/dev/null
```

Thanks.

**Comment by JasoonS** [comment]
I have the exact same error. I'll post the full trace (in case it is useful).

```
Traceback (most recent call last):
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/cursor.py", line 664, in executemany
    return self.execute(stmt)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/cursor.py", line 561, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/connection.py", line 525, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/connection.py", line 427, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 's1hago' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ethgasstation.py", line 516, in update_dataframes
    write_to_sql(alltx, analyzed_block, block_sumdf, mined_blockdf, block)
  File "ethgasstation.py", line 56, in write_to_sql
    post.to_sql(con=engine, name='minedtx2', if_exists='append', index=True)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/pandas/core/generic.py", line 1534, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/pandas/io/sql.py", line 473, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/pandas/io/sql.py", line 1156, in to_sql
    table.insert(chunksize)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/pandas/io/sql.py", line 670, in insert
    self._execute_insert(conn, keys, chunk_iter)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/pandas/io/sql.py", line 645, in _execute_insert
    conn.execute(self.insert_statement(), data)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/cursor.py", line 664, in executemany
    return self.execute(stmt)
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/cursor.py", line 561, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/connection.py", line 525, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/home/jasoons/.virtualenvs/myenv/lib/python3.6/site-packages/mysql/connector/connection.py", line 427, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 's1hago' in 'field list' [SQL: 'INSERT INTO minedtx2 (`index`, block_mined, block_posted, chained, dump, `expectedTime`, `expectedWait`, from_address, gas_offered, gas_price, gp10th, hashpower_accepting, `hgXhpa`, high_gas_offered, highgas2, ico, mined_probability, miner, nonce, num_from, num_to, pct_limit, removed_block, round_gp_10gwei, s1hago, s5mago, time_mined, time_posted, to_address, tx_atabove, wait_blocks) VALUES (%(index)s, %(block_mined)s, %(block_posted)s, %(chained)s, %(dump)s, %(expectedTime)s, %(expectedWait)s, %(from_address)s, %(gas_offered)s, %(gas_price)s, %(gp10th)s, %(hashpower_accepting)s, %(hgXhpa)s, %(high_gas_offered)s, %(highgas2)s, %(ico)s, %(mined_probability)s, %(miner)s, %(nonce)s, %(num_from)s, %(num_to)s, %(pct_limit)s, %(removed_block)s, %(round_gp_10gwei)s, %(s1hago)s, %(s5mago)s, %(time_mined)s, %(time_posted)s, %(to_address)s, %(tx_atabove)s, %(wait_blocks)s)'] [parameters: ({'index': '0x19ce0e1334335a4736eae4f5431a64b5a261e9b2c2fd01404003ee01f56ccdf2', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x1b52C9A5d780972065c79f2F72795988f09C251A', 'gas_offered': 31000.0, 'gas_price': 51000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 0.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 510.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x390dE26d772D2e2005C6d1d24afC902bae37a4bB', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x1ec70efccda5c695a9103e6a9a9fa79fd10cdaaeaf36d5d1116cc3b07e77380d', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x488038D8ee52114732Fe9A9E22993c39C4883D9F', 'gas_offered': 21000.0, 'gas_price': 21000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 36.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 210.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x20782dB20A69fC2b70064277df7E84E7C93554da', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x1ed6f6042bd1c9b0594d92314a87d29890c0423d3044d0cc964858b5976c2afa', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0xBC5e0E93A3EaB3CFBD552a25a2de5fB74e32EdB3', 'gas_offered': 60000.0, 'gas_price': 20000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 4.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 200.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x5d65D971895Edc438f465c17DB6992698a52318D', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x26c7fb031d70acda7e629847ad23aa43b26f6b6757490f425f33148b308e9c43', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0xa596E971d485D44823442fFfA5E1378e833D15dA', 'gas_offered': 37609.0, 'gas_price': 1000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 0.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 10.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0xD0a4b8946Cb52f0661273bfbC6fD0E0C75Fc6433', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x28bc67b80150b1559229082ff841c79b5effaa55bfc71987186610703acfd2c9', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0xF681251b6d5937C3f03c050bEC11B32B2cF74b48', 'gas_offered': 21000.0, 'gas_price': 40000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 0.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 400.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x70faa28A6B8d6829a4b1E649d26eC9a2a39ba413', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x35ad8dccac3232555b6876a599d3d19295283d8cdd666176f140de8b524551e8', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0xA54577AbDcD0eB13f04D5fC1061326eadCF6c3E6', 'gas_offered': 21000.0, 'gas_price': 58000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 3225.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 580.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0xE9F1719eF3bb5318Ce11748E7236330E8203C57d', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x3e3eceefe60777084e9ac0ce971265cb48b8a8bf84e674c5e6f8f92545f4e6a3', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x00DEd958fF1F221884Ddb54cfEbc5Bc354D654ba', 'gas_offered': 90000.0, 'gas_price': 20000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 0.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 200.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x05b8448BE5Ead2cf30c3B314C333Ae0973140075', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0x41c94de7e963076a84721ab07d99133aaf7d1b92a8ee1f468457b85022d6a65d', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x27340A802cbDf612384b0749B767B5B6C9A97513', 'gas_offered': 250000.0, 'gas_price': 6000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 153.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 60.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x82563d2Fb6d1D337D3D7Be1FFA5ac9c272F04f37', 'tx_atabove': None, 'wait_blocks': None}  ... displaying 10 of 32 total bound parameter sets ...  {'index': '0xfb87c77d6fc900c7bc241262922b2239218e55a9fe86b6ca163bc5f66e56e795', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x416299AAde6443e6F6e8ab67126e65a7F606eeF5', 'gas_offered': 50000.0, 'gas_price': 30000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 47753.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 300.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0xDe65FF8c91f1B5067A3A792236A46BF6E31D6027', 'tx_atabove': None, 'wait_blocks': None}, {'index': '0xffbd9113c6de841bc22d62f5c89bbfd17cedd9416972d3335058887ba5d62303', 'block_mined': 4811663.0, 'block_posted': None, 'chained': None, 'dump': None, 'expectedTime': None, 'expectedWait': None, 'from_address': '0x52bc44d5378309EE2abF1539BF71dE1b7d7bE3b5', 'gas_offered': 50000.0, 'gas_price': 1000000000.0, 'gp10th': None, 'hashpower_accepting': None, 'hgXhpa': None, 'high_gas_offered': None, 'highgas2': None, 'ico': None, 'mined_probability': None, 'miner': '0xb2930b35844a230f00e51431acae96fe543a0347', 'nonce': 4314765.0, 'num_from': None, 'num_to': None, 'pct_limit': None, 'removed_block': None, 'round_gp_10gwei': 10.0, 's1hago': None, 's5mago': None, 'time_mined': 1514452932.0, 'time_posted': None, 'to_address': '0x0F13FBf6596300d4528eF010F58Ae2B2BDC47212', 'tx_atabove': None, 'wait_blocks': None})]
```

**Comment by bamos01** [comment]
Yes- this was a new variable added- probably the simplest thing to do is delete your existing mysql files and let them be recreated.  I added the new code to egs.py

**Comment by 10a7** [comment]
Closing this issue as now resolved
