### ISSUE TITLE
NaNs

### ISSUE THREAD

**Issue by gyohng** [ethgasstation/ethgasstation-backend#32]
Yesterday (Jul 14) the network went crazy, the gas prices went up to 100 gwei and higher, and both latest branches ethgasstation-backend and oracle were predicting 'nan' for some values. Also, occasionally it would cause an exception. Here's some excerpt from the log:

```
{'fast': 1420, 'fastest': 1470, 'nomine': None, 'safeLow': nan, 'average': nan, 'block_time': 11.692307692307692, 'blockNum': 5963675,
 'speed': 0.99726616439117566}
[2018-07-14 18:03:59] [INFO] getting txpool hashes at block 5963680 ...
[2018-07-14 18:04:43] [INFO] done. length = 126590
[2018-07-14 18:04:43] [INFO] listening for new transactions at block 5963681....
[2018-07-14 18:04:45] [INFO] now processing block 5963676
[2018-07-14 18:04:45] [INFO] submitted tx: 0
[2018-07-14 18:04:46] [INFO] num mined in 5963673 = 80
[2018-07-14 18:04:46] [INFO] num seen in 5963673 = 8
[2018-07-14 18:04:46] [INFO] # of tx submitted ~ 5mago = 135
[2018-07-14 18:04:46] [INFO] # of tx submitted ~ 30mago = 406
[2018-07-14 18:04:46] [INFO] txpool block length 17977
[2018-07-14 18:04:46] [INFO] safelow: 1000
[2018-07-14 18:04:46] [INFO] avg: 1030
cannot convert float NaN to integer
[2018-07-14 18:04:46] [ERROR]Traceback (most recent call last):
  File "/root/ethgasstation-backend/egs/main.py", line 59, in master_control
    gaspricereport.get_wait(predictiontable.predictiondf)
  File "/root/ethgasstation-backend/egs/egs_ref.py", line 735, in get_wait
    self.gprecs['safeLowWait'] = lookup(self.gprecs['safeLow'])
  File "/root/ethgasstation-backend/egs/egs_ref.py", line 733, in lookup
    wait = round(wait, 1)
UnboundLocalError: local variable 'wait' referenced before assignment

```

**Comment by ethgasstation** [comment]
Fixed - this was problem with looking up in table when gas price was undefined

**Comment by gyohng** [comment]
gasstation-express-oracle did the same thing. is it possible to push the update there as well?
